image: Visual Studio 2017
environment:
  nodejs_version: "LTS"
install:
  - ps: Install-Product node $env:nodejs_version
  - cd web && yarn
build_script:
  - gradlew.bat build
before_test:
  - gradlew.bat ktlint
  - cd web && yarn lint && yarn build
test_script:
  - gradlew.bat test jacocoTestReport
  - cd web && yarn test
