language: java
install:
  - curl -s https://get.sdkman.io | bash
  - sdk install gradle
  - nvm install --lts
  - cd web && yarn
script:
  - cd ..
  - gradle build
  - gradle ktlint
  - gradle test jacocoTestReport
  - cd web
  - yarn lint && yarn build && yarn test
